import React, { useState } from 'react';
import { 
  FileText, 
  Download, 
  Share2, 
  Check, 
  Zap, 
  Droplets, 
  IndianRupee, 
  Leaf, 
  CheckCircle2, 
  TrendingDown, 
  Printer, 
  Calendar, 
  Building2, 
  Award, 
  ArrowRight 
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  Legend 
} from 'recharts';
import { PageId } from '../types';
import { MONTHLY_REPORT_DATA, BUILDING_INFO } from '../data/mockBuildingData';

interface ReportPageProps {
  onNavigate: (page: PageId) => void;
}

export const ReportPage: React.FC<ReportPageProps> = ({ onNavigate }) => {
  const [copiedShare, setCopiedShare] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleDownload = () => {
    // Generate text/markdown formatted report download
    const reportContent = `
=====================================================
ECOTWIN — BUILDING SUSTAINABILITY & RESOURCE REPORT
Facility: ${BUILDING_INFO.name}
Report Period: ${MONTHLY_REPORT_DATA.period}
=====================================================

EXECUTIVE SUMMARY:
- Total Energy Saved: ${MONTHLY_REPORT_DATA.totalEnergySavedKwh} kWh (${MONTHLY_REPORT_DATA.energyReductionPct}% reduction)
- Total Water Conserved: ${MONTHLY_REPORT_DATA.totalWaterSavedLiters.toLocaleString()} Liters (${MONTHLY_REPORT_DATA.waterReductionPct}% reduction)
- Projected Monthly Rupee Savings: ₹${MONTHLY_REPORT_DATA.totalCostSavedINR.toLocaleString()}
- Total Carbon Emissions Avoided: ${MONTHLY_REPORT_DATA.totalCo2AvoidedKg} kg CO2e
- Anomalies Resolved: ${MONTHLY_REPORT_DATA.anomaliesResolved} of 7
- System IoT Telemetry Uptime: ${MONTHLY_REPORT_DATA.systemUptimePct}%

KEY ACHIEVEMENTS:
1. 12% reduction in energy consumption
2. 8% reduction in water consumption
3. ₹18,600 projected monthly savings
4. 4 anomalies resolved

RESOLVED INTERVENTIONS AUDIT:
${MONTHLY_REPORT_DATA.resolvedInterventions
  .map(
    (i) =>
      `• [${i.date}] ${i.name} -> Saved ₹${i.savingsINR}/mo (${i.energyKwh} kWh, ${i.waterL} L water) [Status: ${i.status}]`
  )
  .join('\n')}

Audit Standard: IPMVP Option C & ASHRAE Guideline 14 Normalized Weather Regression.
Generated by VECNA Smart Building Twin on ${new Date().toLocaleDateString()}.
=====================================================
`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `VECNA_Sustainability_Report_${BUILDING_INFO.name.replace(/\s+/g, '_')}_${MONTHLY_REPORT_DATA.period.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  const handleShare = () => {
    const shareText = `VECNA Sustainability Report (${BUILDING_INFO.name}): 12% energy reduction, 8% water saved, ₹18,600/mo waste eliminated, 4 anomalies resolved!`;
    navigator.clipboard.writeText(shareText);
    setCopiedShare(true);
    setTimeout(() => setCopiedShare(false), 3000);
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-4 pb-12">
      {/* Header with Title & Action Buttons (Required by Prompt) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs uppercase font-bold tracking-wider text-emerald-800 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/60 px-2.5 py-1 rounded-md border border-emerald-200/60 dark:border-emerald-800/60">
              Executive ESG Document
            </span>
            <span className="text-xs text-slate-500 dark:text-slate-400">• Period: {MONTHLY_REPORT_DATA.period}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight mt-1">
            Building Sustainability Report
          </h1>
          <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 mt-1">
            Comprehensive audit for {BUILDING_INFO.name} summarizing verified resource waste elimination and financial ROI.
          </p>
        </div>

        {/* Buttons: Download Report & Share Report (Required by Prompt) */}
        <div className="flex items-center gap-2.5">
          <button
            id="download-report-btn"
            onClick={handleDownload}
            className="px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 dark:bg-emerald-600 dark:hover:bg-emerald-500 text-white text-xs font-bold flex items-center gap-2 transition-colors cursor-pointer shadow-xs"
          >
            {downloadSuccess ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400 dark:text-white" />
                <span>Downloaded!</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5 text-emerald-400 dark:text-white" />
                <span>Download Report</span>
              </>
            )}
          </button>

          <button
            id="share-report-btn"
            onClick={handleShare}
            className="px-4 py-2.5 rounded-xl bg-white hover:bg-slate-50 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-bold border border-slate-200 dark:border-slate-700 flex items-center gap-2 transition-colors cursor-pointer shadow-xs"
          >
            {copiedShare ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                <span>Link Copied!</span>
              </>
            ) : (
              <>
                <Share2 className="w-3.5 h-3.5 text-slate-500 dark:text-slate-400" />
                <span>Share Report</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* CORE REPORT METRICS (Energy savings, Water savings, Cost savings, CO2 reduction, Interventions completed, Anomalies resolved) */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <Zap className="w-3.5 h-3.5 text-amber-500" /> Energy Savings
          </div>
          <div className="text-xl font-extrabold text-slate-900 dark:text-white">
            {MONTHLY_REPORT_DATA.totalEnergySavedKwh} <span className="text-xs font-normal text-slate-500 dark:text-slate-400">kWh</span>
          </div>
          <div className="text-[10px] text-emerald-600 dark:text-emerald-400 font-bold mt-1">
            ↓ {MONTHLY_REPORT_DATA.energyReductionPct}% Reduction
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <Droplets className="w-3.5 h-3.5 text-sky-500" /> Water Savings
          </div>
          <div className="text-xl font-extrabold text-slate-900 dark:text-white">
            {MONTHLY_REPORT_DATA.totalWaterSavedLiters.toLocaleString()} <span className="text-xs font-normal text-slate-500 dark:text-slate-400">L</span>
          </div>
          <div className="text-[10px] text-emerald-600 dark:text-emerald-400 font-bold mt-1">
            ↓ {MONTHLY_REPORT_DATA.waterReductionPct}% Reduction
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <IndianRupee className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> Cost Savings
          </div>
          <div className="text-xl font-extrabold text-emerald-700 dark:text-emerald-400">
            ₹{MONTHLY_REPORT_DATA.totalCostSavedINR.toLocaleString()}
          </div>
          <div className="text-[10px] text-slate-500 dark:text-slate-400 mt-1">
            Monthly Run-Rate
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <Leaf className="w-3.5 h-3.5 text-teal-600 dark:text-teal-400" /> CO₂ Reduction
          </div>
          <div className="text-xl font-extrabold text-slate-900 dark:text-white">
            {MONTHLY_REPORT_DATA.totalCo2AvoidedKg} <span className="text-xs font-normal text-slate-500 dark:text-slate-400">kg</span>
          </div>
          <div className="text-[10px] text-teal-600 dark:text-teal-400 mt-1">
            Carbon offsets
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <Award className="w-3.5 h-3.5 text-indigo-600 dark:text-indigo-400" /> Interventions
          </div>
          <div className="text-xl font-extrabold text-slate-900 dark:text-white">
            4 <span className="text-xs font-normal text-slate-500 dark:text-slate-400">Done</span>
          </div>
          <div className="text-[10px] text-indigo-600 dark:text-indigo-400 font-bold mt-1">
            100% Verified
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="text-[11px] font-medium text-slate-500 dark:text-slate-400 flex items-center gap-1 mb-1">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> Anomalies Resolved
          </div>
          <div className="text-xl font-extrabold text-emerald-700 dark:text-emerald-400">
            {MONTHLY_REPORT_DATA.anomaliesResolved} <span className="text-xs font-normal text-slate-500 dark:text-slate-400">of 7</span>
          </div>
          <div className="text-[10px] text-slate-500 dark:text-slate-400 mt-1">
            3 in active triage
          </div>
        </div>
      </div>

      {/* KEY ACHIEVEMENTS (Required by Prompt) */}
      <div className="bg-gradient-to-r from-emerald-50/80 via-white to-teal-50/60 dark:from-emerald-950/40 dark:via-slate-900 dark:to-teal-950/30 rounded-2xl p-6 border border-emerald-200 dark:border-emerald-800/80 shadow-xs">
        <div className="flex items-center gap-2 mb-4">
          <Award className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">Key achievements</h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-4 bg-white dark:bg-slate-900/90 rounded-xl border border-emerald-100 dark:border-emerald-800/60 shadow-xs">
            <div className="text-2xl font-extrabold text-slate-900 dark:text-white">12%</div>
            <div className="text-xs font-semibold text-emerald-800 dark:text-emerald-300 mt-0.5">
              reduction in energy consumption
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
              Driven by HVAC setback rescheduling on Floors 2 & 3.
            </p>
          </div>

          <div className="p-4 bg-white dark:bg-slate-900/90 rounded-xl border border-emerald-100 dark:border-emerald-800/60 shadow-xs">
            <div className="text-2xl font-extrabold text-slate-900 dark:text-white">8%</div>
            <div className="text-xs font-semibold text-emerald-800 dark:text-emerald-300 mt-0.5">
              reduction in water consumption
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
              Secured by repairing Floor 1 restroom solenoid leak.
            </p>
          </div>

          <div className="p-4 bg-white dark:bg-slate-900/90 rounded-xl border border-emerald-100 dark:border-emerald-800/60 shadow-xs">
            <div className="text-2xl font-extrabold text-emerald-700 dark:text-emerald-400">₹18,600</div>
            <div className="text-xs font-semibold text-slate-900 dark:text-slate-200 mt-0.5">
              projected monthly savings
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
              Direct recurring utility budget operational recovery.
            </p>
          </div>

          <div className="p-4 bg-white dark:bg-slate-900/90 rounded-xl border border-emerald-100 dark:border-emerald-800/60 shadow-xs">
            <div className="text-2xl font-extrabold text-slate-900 dark:text-white">4</div>
            <div className="text-xs font-semibold text-emerald-800 dark:text-emerald-300 mt-0.5">
              anomalies resolved
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-1">
              Zero human maintenance complaints or student discomfort.
            </p>
          </div>
        </div>
      </div>

      {/* MONTHLY TREND CHART (Required by prompt) */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-4 mb-4 border-b border-slate-100 dark:border-slate-800">
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Monthly Resource Savings Trend (April – September 2026)
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Tracking cumulative monthly kilowatt-hours conserved and water savings as VECNA was deployed.
            </p>
          </div>

          <div className="flex items-center gap-4 text-xs">
            <div className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-xs bg-amber-500 inline-block"></span>
              <span className="text-slate-600 dark:text-slate-300 font-medium">Energy Saved (kWh)</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-xs bg-sky-500 inline-block"></span>
              <span className="text-slate-600 dark:text-slate-300 font-medium">Water Saved (x100 L)</span>
            </div>
          </div>
        </div>

        <div className="h-72 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart 
              data={MONTHLY_REPORT_DATA.monthlyTrends.map((d) => ({
                ...d,
                waterSavedNormalized: Math.round(d.waterSaved / 100),
              }))} 
              margin={{ top: 10, right: 20, left: 0, bottom: 0 }}
            >
              <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.3} />
              <XAxis dataKey="month" stroke="#94a3b8" fontSize={11} />
              <YAxis stroke="#94a3b8" fontSize={11} />
              <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderRadius: '8px', color: '#fff', fontSize: '12px', border: 'none' }} />
              <Bar dataKey="energySaved" fill="#f59e0b" name="Energy Saved (kWh)" radius={[4, 4, 0, 0]} />
              <Bar dataKey="waterSavedNormalized" fill="#0ea5e9" name="Water Saved (x100 L)" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* RESOLVED INTERVENTIONS TABLE */}
      <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 border border-slate-200 dark:border-slate-800 shadow-xs">
        <div className="pb-3 mb-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-white">
              Completed Interventions Audit Trail
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Verified actions successfully registered on campus hardware.
            </p>
          </div>
          <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
            4 Verified Records
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-400 font-semibold uppercase tracking-wider text-[10px]">
                <th className="pb-3">Action Description</th>
                <th className="pb-3">Resolution Date</th>
                <th className="pb-3">Energy Impact</th>
                <th className="pb-3">Water Impact</th>
                <th className="pb-3">Monthly Return</th>
                <th className="pb-3 text-right">Audit Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800 font-medium">
              {MONTHLY_REPORT_DATA.resolvedInterventions.map((item, idx) => (
                <tr key={idx} className="hover:bg-slate-50/80 dark:hover:bg-slate-800/50 transition-colors">
                  <td className="py-3 text-slate-900 dark:text-white font-bold">{item.name}</td>
                  <td className="py-3 text-slate-500 dark:text-slate-400">{item.date}, 2026</td>
                  <td className="py-3 text-amber-700 dark:text-amber-400 font-semibold">{item.energyKwh} kWh</td>
                  <td className="py-3 text-sky-700 dark:text-sky-400 font-semibold">{item.waterL > 0 ? `${item.waterL.toLocaleString()} L` : '—'}</td>
                  <td className="py-3 text-emerald-700 dark:text-emerald-400 font-bold">₹{item.savingsINR.toLocaleString()}</td>
                  <td className="py-3 text-right">
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                      <CheckCircle2 className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
                      {item.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
